
project_id = "zsmoutzjhqjgjehaituw"

[functions.shopify-auth]
verify_jwt = false

[functions.shopify-webhook] 
verify_jwt = false

[functions.popup-config]
verify_jwt = false

[functions.popup-track]
verify_jwt = false

[functions.install-script]
verify_jwt = false
