
project_id = "zsmoutzjhqjgjehaituw"

[functions.shopify-auth]
verify_jwt = false

[functions.shopify-webhook] 
verify_jwt = false

[functions.popup-config]
verify_jwt = false

[functions.popup-track]
verify_jwt = false

[functions.install-script]
verify_jwt = false

[functions.popup-actions]
verify_jwt = false

[functions.popup-delete]
verify_jwt = false

[functions.popup-simple]
verify_jwt = false

[functions.popup-edit]
verify_jwt = false

[functions.popup-create]
verify_jwt = false

[functions.popup-update]
verify_jwt = false

[functions.install-direct]
verify_jwt = false

[functions.popup-script]
verify_jwt = false

[functions.popup-embed-public]
verify_jwt = false

[functions.install-script-direct]
verify_jwt = false

[functions.install-script-public]
verify_jwt = false

[functions.auto-install]
verify_jwt = false

[functions.check-scripts]
verify_jwt = false

[functions.fix-popup-trigger]
verify_jwt = false

[functions.analyze-popup-types]
verify_jwt = false

[functions.create-exit-intent-popup]
verify_jwt = false
