// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsmoutzjhqjgjehaituw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzbW91dHpqaHFqZ2plaGFpdHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTQzOTgsImV4cCI6MjA2NjM3MDM5OH0.9lmCU7ttsDYn62CeyTZ1rnogFWlpqQGfQ8exwjIKIk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);